[workspace]
resolver = "3"
members = ["library/*", "module/*", "starter/*", "desktop", "ios", "integration-test/*", "buildsrc"]
default-members = ["desktop"]

[workspace.package]
version = "0.2.0"
edition = "2024"
publish = false

[workspace.dependencies]
bevy = { version = "0.19.1", default-features = false }
serde = { version = "1", features = ["derive"] }
config_rs = { package = "config", version = "0.15", default-features = false, features = ["toml"] }
entropybox_core = { path = "library/core", package = "core" }
entropybox_world = { path = "module/world", package = "world" }
entropybox_population = { path = "module/population", package = "population" }
entropybox_society = { path = "module/society", package = "society" }
entropybox_economy = { path = "module/economy", package = "economy" }
entropybox_finance = { path = "module/finance", package = "finance" }
entropybox_politics = { path = "module/politics", package = "politics" }
entropybox_debug = { path = "module/debug", package = "debug" }
entropybox_simulation = { path = "starter/simulation", package = "simulation" }
entropybox = { path = "desktop", package = "desktop" }

[workspace.lints.clippy]
too_many_arguments = "allow"
type_complexity = "allow"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"
strip = true
