[package]
name = "politics"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
bevy = { workspace = true }
econbox_core = { workspace = true }
econbox_society = { workspace = true }
econbox_economy = { workspace = true }
econbox_finance = { workspace = true }

[lints]
workspace = true
