[package]
name = "desktop"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "entropybox"
path = "src/main.rs"

[dependencies]
bevy = { workspace = true, features = ["2d", "ui", "audio"] }
config_rs = { workspace = true }
serde = { workspace = true }
debug = { workspace = true, optional = true }
simulation = { workspace = true }

[features]
dev = ["dep:debug"]
fast-link = ["bevy/dynamic_linking"]

[lints]
workspace = true
