[package]
name = "desktop"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
name = "entropybox"
path = "src/lib.rs"

[[bin]]
name = "entropybox"
path = "src/main.rs"

[dependencies]
bevy = { workspace = true, features = ["2d", "ui", "audio"] }
config_rs = { workspace = true }
serde = { workspace = true }
entropybox_debug = { workspace = true, optional = true }
entropybox_simulation = { workspace = true }

[features]
dev = ["dep:entropybox_debug"]
fast-link = ["bevy/dynamic_linking"]

[lints]
workspace = true
